version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: evento
    environment:
      POSTGRES_DB: evento
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5440:5432"